# CYBERML Project

In [1]:
import pandas as pd
import numpy as np

DATA_FOLDER = './data/'
ATTACK_FOLDER = 'attack_data/'
BENIGN_FOLDER = 'benign_data/'

## Load data

In [2]:
attack_data = pd.read_csv(DATA_FOLDER + ATTACK_FOLDER + 'attack_samples_1sec.csv')
attack_data.head()

device_name         device_mac                           label_full  label1  \
0       edge1  dc:a6:32:dc:27:d4  attack_ddos_syn-flood-port-80_edge1  attack   
1       edge1  dc:a6:32:dc:27:d4  attack_ddos_syn-flood-port-80_edge1  attack   
2       edge1  dc:a6:32:dc:27:d4  attack_ddos_syn-flood-port-80_edge1  attack   
3       edge1  dc:a6:32:dc:27:d4  attack_ddos_syn-flood-port-80_edge1  attack   
4       edge1  dc:a6:32:dc:27:d4  attack_ddos_syn-flood-port-80_edge1  attack   

  label2             label3                  label4  \
0   ddos  syn-flood-port-80  ddos_syn-flood-port-80   
1   ddos  syn-flood-port-80  ddos_syn-flood-port-80   
2   ddos  syn-flood-port-80  ddos_syn-flood-port-80   
3   ddos  syn-flood-port-80  ddos_syn-flood-port-80   
4   ddos  syn-flood-port-80  ddos_syn-flood-port-80   

                                           timestamp  \
0  2025-01-23T15:31:10.709000Z_2025-01-23T15:31:1...   
1  2025-01-23T15:31:11.709000Z_2025-01-23T15:31:1...   
2  2025-01-23T15:31:12.709000Z_2025-01-23T15:31:1...   
3  2025-01-23T15:31:13.709000Z_2025-01-23T15:31:1...   
4  2025-01-23T15:31:14.709000Z_2025-01-23T15:31:1...   

               timestamp_start                timestamp_end  ...  \
0  2025-01-23T15:31:10.709000Z  2025-01-23T15:31:11.709000Z  ...   
1  2025-01-23T15:31:11.709000Z  2025-01-23T15:31:12.709000Z  ...   
2  2025-01-23T15:31:12.709000Z  2025-01-23T15:31:13.709000Z  ...   
3  2025-01-23T15:31:13.709000Z  2025-01-23T15:31:14.709000Z  ...   
4  2025-01-23T15:31:14.709000Z  2025-01-23T15:31:15.709000Z  ...   

   network_time-delta_min  network_time-delta_std_deviation  network_ttl_avg  \
0                     0.0                               0.0              0.0   
1                     0.0                               0.0              0.0   
2                     0.0                               0.0              0.0   
3                     0.0                               0.0              0.0   
4                     0.0                               0.0              0.0   

   network_ttl_max network_ttl_min  network_ttl_std_deviation  \
0              0.0             0.0                        0.0   
1              0.0             0.0                        0.0   
2              0.0             0.0                        0.0   
3              0.0             0.0                        0.0   
4              0.0             0.0                        0.0   

   network_window-size_avg  network_window-size_max  network_window-size_min  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   network_window-size_std_deviation  
0                                0.0  
1                                0.0  
2                                0.0  
3                                0.0  
4                                0.0  

[5 rows x 94 columns]

In [3]:
benign_data = pd.read_csv(DATA_FOLDER + BENIGN_FOLDER + 'benign_samples_1sec.csv')
benign_data.head()

device_name         device_mac             label_full  label1  label2  \
0      router  28:87:ba:bd:c6:6c  benign_whole-network3  benign  benign   
1      router  28:87:ba:bd:c6:6c  benign_whole-network3  benign  benign   
2      router  28:87:ba:bd:c6:6c  benign_whole-network3  benign  benign   
3      router  28:87:ba:bd:c6:6c  benign_whole-network3  benign  benign   
4      router  28:87:ba:bd:c6:6c  benign_whole-network3  benign  benign   

   label3  label4                                          timestamp  \
0  benign  benign  2025-09-09T14:09:40.400000Z_2025-09-09T14:09:4...   
1  benign  benign  2025-09-09T14:09:41.400000Z_2025-09-09T14:09:4...   
2  benign  benign  2025-09-09T14:09:42.400000Z_2025-09-09T14:09:4...   
3  benign  benign  2025-09-09T14:09:43.400000Z_2025-09-09T14:09:4...   
4  benign  benign  2025-09-09T14:09:44.400000Z_2025-09-09T14:09:4...   

               timestamp_start                timestamp_end  ...  \
0  2025-09-09T14:09:40.400000Z  2025-09-09T14:09:41.400000Z  ...   
1  2025-09-09T14:09:41.400000Z  2025-09-09T14:09:42.400000Z  ...   
2  2025-09-09T14:09:42.400000Z  2025-09-09T14:09:43.400000Z  ...   
3  2025-09-09T14:09:43.400000Z  2025-09-09T14:09:44.400000Z  ...   
4  2025-09-09T14:09:44.400000Z  2025-09-09T14:09:45.400000Z  ...   

   network_time-delta_min  network_time-delta_std_deviation  network_ttl_avg  \
0                     0.0                          0.006059        62.800000   
1                     0.0                          0.016469        62.500000   
2                     0.0                          0.034312        61.571429   
3                     0.0                          0.012790        62.500000   
4                     0.0                          0.017764        62.800000   

   network_ttl_max network_ttl_min  network_ttl_std_deviation  \
0             64.0            61.0                   1.469694   
1             64.0            61.0                   1.500000   
2             64.0            53.0                   3.736199   
3             64.0            61.0                   1.500000   
4             64.0            61.0                   1.469694   

   network_window-size_avg  network_window-size_max  network_window-size_min  \
0              1870.500000                   3081.0                    660.0   
1              1870.500000                   3081.0                    660.0   
2              2441.285714                   4736.0                    135.0   
3              1870.500000                   3081.0                    660.0   
4              2112.600000                   3081.0                    660.0   

   network_window-size_std_deviation  
0                        1210.500000  
1                        1210.500000  
2                        1813.237335  
3                        1210.500000  
4                        1186.042933  

[5 rows x 94 columns]

In [4]:
print("Attack Data Shape:", attack_data.shape)
print("Benign Data Shape:", benign_data.shape)

Attack Data Shape: (90391, 94)
Benign Data Shape: (136800, 94)


In [5]:
# Merge both datasets for training
combined_data = pd.concat([attack_data, benign_data], ignore_index=True)
combined_data = combined_data.sample(frac=1).reset_index(drop=True)  # Shuffle the data

print("Combined Data Shape:", combined_data.shape)
combined_data.head()

Combined Data Shape: (227191, 94)


device_name         device_mac                             label_full  \
0      plug-all-rpb  c4:dd:57:0d:f2:76                  benign_whole-network3   
1      dekco-camera  44:29:1e:5c:de:12                  benign_whole-network3   
2  plug-all-sensors  d4:a6:51:82:98:a8                  benign_whole-network3   
3       plug-motion  d4:a6:51:1d:74:3a                  benign_whole-network3   
4    wisenet-camera  00:09:18:6d:73:b9  attack_recon_ping-sweep_whole-network   

   label1  label2      label3            label4  \
0  benign  benign      benign            benign   
1  benign  benign      benign            benign   
2  benign  benign      benign            benign   
3  benign  benign      benign            benign   
4  attack   recon  ping-sweep  recon_ping-sweep   

                                           timestamp  \
0  2025-09-09T14:42:19.400000Z_2025-09-09T14:42:2...   
1  2025-09-09T15:04:43.400000Z_2025-09-09T15:04:4...   
2  2025-09-09T14:12:29.400000Z_2025-09-09T14:12:3...   
3  2025-09-09T15:04:33.400000Z_2025-09-09T15:04:3...   
4  2025-01-15T13:11:33.293000Z_2025-01-15T13:11:3...   

               timestamp_start                timestamp_end  ...  \
0  2025-09-09T14:42:19.400000Z  2025-09-09T14:42:20.400000Z  ...   
1  2025-09-09T15:04:43.400000Z  2025-09-09T15:04:44.400000Z  ...   
2  2025-09-09T14:12:29.400000Z  2025-09-09T14:12:30.400000Z  ...   
3  2025-09-09T15:04:33.400000Z  2025-09-09T15:04:34.400000Z  ...   
4  2025-01-15T13:11:33.293000Z  2025-01-15T13:11:34.293000Z  ...   

   network_time-delta_min  network_time-delta_std_deviation  network_ttl_avg  \
0                0.000000                               0.0              0.0   
1                0.000000                               0.0              0.0   
2                0.000000                               0.0              0.0   
3                0.003910                               0.0            255.0   
4                0.002366                               0.0              0.0   

   network_ttl_max network_ttl_min  network_ttl_std_deviation  \
0              0.0             0.0                        0.0   
1              0.0             0.0                        0.0   
2              0.0             0.0                        0.0   
3            255.0           255.0                        0.0   
4              0.0             0.0                        0.0   

   network_window-size_avg  network_window-size_max  network_window-size_min  \
0                      0.0                      0.0                      0.0   
1                      0.0                      0.0                      0.0   
2                      0.0                      0.0                      0.0   
3                      0.0                      0.0                      0.0   
4                      0.0                      0.0                      0.0   

   network_window-size_std_deviation  
0                                0.0  
1                                0.0  
2                                0.0  
3                                0.0  
4                                0.0  

[5 rows x 94 columns]

## Try learning

### Prepare data

In [6]:
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC
from sklearn.metrics import classification_report, confusion_matrix, matthews_corrcoef, average_precision_score, balanced_accuracy_score

# Replace all NaN values with zeros
combined_data.fillna(0, inplace=True)

# Copy data
encoded_data = combined_data.copy()

encoded_values = {}

# Turn label data into integers
label_columns = ['label1', 'label2', 'label3', 'label4']
for col in label_columns:
    encoded_data[col], uniques = pd.factorize(encoded_data[col])
    encoded_values[col] = dict(enumerate(uniques))

# Remove non numerical columns
encoded_data = encoded_data.select_dtypes(include=[np.number])
encoded_data.head()

encoded_data

label1  label2  label3  label4  log_data-ranges_avg  \
0            0       0       0       0                  0.0   
1            0       0       0       0                  0.0   
2            0       0       0       0                  0.0   
3            0       0       0       0                  0.0   
4            1       1       1       1                  0.0   
...        ...     ...     ...     ...                  ...   
227186       0       0       0       0               1023.0   
227187       0       0       0       0                  0.0   
227188       1       7      22      25                  0.0   
227189       1       6      35      45                  0.0   
227190       0       0       0       0                916.0   

        log_data-ranges_max  log_data-ranges_min  \
0                       0.0                  0.0   
1                       0.0                  0.0   
2                       0.0                  0.0   
3                       0.0                  0.0   
4                       0.0                  0.0   
...                     ...                  ...   
227186               1023.0               1023.0   
227187                  0.0                  0.0   
227188                  0.0                  0.0   
227189                  0.0                  0.0   
227190                916.0                916.0   

        log_data-ranges_std_deviation  log_data-types_count  \
0                                 0.0                     0   
1                                 0.0                     0   
2                                 0.0                     0   
3                                 0.0                     0   
4                                 0.0                     0   
...                               ...                   ...   
227186                            0.0                     1   
227187                            0.0                     0   
227188                            0.0                     0   
227189                            0.0                     0   
227190                            0.0                     2   

        log_interval-messages  ...  network_time-delta_min  \
0                         0.0  ...            0.000000e+00   
1                         0.0  ...            0.000000e+00   
2                         0.0  ...            0.000000e+00   
3                         0.0  ...            3.910000e-03   
4                         0.0  ...            2.365725e-03   
...                       ...  ...                     ...   
227186                    0.0  ...            4.260000e-04   
227187                    0.0  ...            4.870600e-02   
227188                    0.0  ...            3.300000e-08   
227189                    0.0  ...            0.000000e+00   
227190                    0.0  ...            0.000000e+00   

        network_time-delta_std_deviation  network_ttl_avg  network_ttl_max  \
0                               0.000000         0.000000              0.0   
1                               0.000000         0.000000              0.0   
2                               0.000000         0.000000              0.0   
3                               0.000000       255.000000            255.0   
4                               0.000000         0.000000              0.0   
...                                  ...              ...              ...   
227186                          0.033857       159.500000            255.0   
227187                          0.000000         0.000000              0.0   
227188                          0.006008        69.419355            255.0   
227189                          0.007093        64.047619            113.0   
227190                          0.002004       159.500000            255.0   

        network_ttl_min  network_ttl_std_deviation  network_window-size_avg  \
0                   0.0                   0.000000                 0.000000   
1                   0.0      

In [7]:
X = encoded_data.drop(['label1', 'label2', 'label3', 'label4'], axis=1)
y = encoded_data['label1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Supervised Learning

### Train With Gradient Boosting

In [14]:
import xgboost

modelGboost = xgboost.XGBClassifier()

modelGboost.fit(X_train, y_train)

y_pred = modelGboost.predict(X_test)

print("=== Gradient Boosting Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Gradient Boosting Results ===
Confusion matrix:
[[27011    44]
 [ 2507 15877]]
Classification report:
              precision    recall  f1-score   support

           0       0.92      1.00      0.95     27055
           1       1.00      0.86      0.93     18384

    accuracy                           0.94     45439
   macro avg       0.96      0.93      0.94     45439
weighted avg       0.95      0.94      0.94     45439

Matthews Corrcoef: 0.8868
Average precision: 0.9164
Balanced accuracy: 0.9310


### Train with Logistic regression

In [15]:
modelLinear = sklearn.linear_model.LogisticRegression()
modelLinear.fit(X_train, y_train)
y_pred = modelLinear.predict(X_test)

print("=== Logistic Regression Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Logistic Regression Results ===
Confusion matrix:
[[26901   154]
 [ 4982 13402]]
Classification report:
              precision    recall  f1-score   support

           0       0.84      0.99      0.91     27055
           1       0.99      0.73      0.84     18384

    accuracy                           0.89     45439
   macro avg       0.92      0.86      0.88     45439
weighted avg       0.90      0.89      0.88     45439

Matthews Corrcoef: 0.7759
Average precision: 0.8304
Balanced accuracy: 0.8617


/home/baptiste/cyberml/.venv/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


### Train with SVC

In [16]:
model = LinearSVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("=== Linear SVC Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Linear SVC Results ===
Confusion matrix:
[[26810   245]
 [ 4492 13892]]
Classification report:
              precision    recall  f1-score   support

           0       0.86      0.99      0.92     27055
           1       0.98      0.76      0.85     18384

    accuracy                           0.90     45439
   macro avg       0.92      0.87      0.89     45439
weighted avg       0.91      0.90      0.89     45439

Matthews Corrcoef: 0.7915
Average precision: 0.8414
Balanced accuracy: 0.8733


## Unsupervised learning

### Isolation Forest

In [17]:
model = sklearn.ensemble.IsolationForest(contamination=0.39)
model.fit(X_train)

y_pred = model.predict(X_test)

y_pred = (y_pred == (-1 if encoded_values["label1"][1] == "attack" else 1)).astype(int)

print("=== Isolation Forest Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Isolation Forest Results ===
Confusion matrix:
[[21654  5401]
 [ 5878 12506]]
Classification report:
              precision    recall  f1-score   support

           0       0.79      0.80      0.79     27055
           1       0.70      0.68      0.69     18384

    accuracy                           0.75     45439
   macro avg       0.74      0.74      0.74     45439
weighted avg       0.75      0.75      0.75     45439

Matthews Corrcoef: 0.4828
Average precision: 0.6044
Balanced accuracy: 0.7403


### SVM

In [18]:
X_train_sampled = X_train.sample(frac=0.1)
model = sklearn.svm.OneClassSVM(kernel="linear", shrinking=False)
model.fit(X_train_sampled)

y_pred = model.predict(X_test)

y_pred = (y_pred == 1).astype(int)

print("=== One-Class SVM Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== One-Class SVM Results ===
Confusion matrix:
[[18344  8711]
 [ 4197 14187]]
Classification report:
              precision    recall  f1-score   support

           0       0.81      0.68      0.74     27055
           1       0.62      0.77      0.69     18384

    accuracy                           0.72     45439
   macro avg       0.72      0.72      0.71     45439
weighted avg       0.74      0.72      0.72     45439

Matthews Corrcoef: 0.4415
Average precision: 0.5705
Balanced accuracy: 0.7249


### Local Outlier Factor

In [19]:
import sklearn.neighbors

X_train_sampled_2 = X_train.sample(frac=0.5)

model = sklearn.neighbors.LocalOutlierFactor(novelty=True, contamination=0.39)
model.fit(X_train_sampled_2)

y_pred = model.predict(X_test)

y_pred = (y_pred == (-1 if encoded_values["label1"][1] == "attack" else 1)).astype(int)

print("=== Local Outlier Factor Results ===")
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred)
mcc = matthews_corrcoef(y_test, y_pred)
ap = average_precision_score(y_test, y_pred)
bal = balanced_accuracy_score(y_test, y_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Average precision: {ap:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

/home/baptiste/cyberml/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LocalOutlierFactor was fitted with feature names
  warnings.warn(


=== Local Outlier Factor Results ===
Confusion matrix:
[[19679  7376]
 [ 7370 11014]]
Classification report:
              precision    recall  f1-score   support

           0       0.73      0.73      0.73     27055
           1       0.60      0.60      0.60     18384

    accuracy                           0.68     45439
   macro avg       0.66      0.66      0.66     45439
weighted avg       0.68      0.68      0.68     45439

Matthews Corrcoef: 0.3265
Average precision: 0.5210
Balanced accuracy: 0.6632


## Attack Type Classification

In [20]:
y_type = encoded_data['label2']
y_type_train = y_type.loc[X_train.index]
y_type_test = y_type.loc[X_test.index]

label2_mapping = encoded_values['label2']
labels_sorted = sorted(label2_mapping.keys())
target_names = [label2_mapping[k] for k in labels_sorted]

print("Label2 mapping:", label2_mapping)
print(f"Number of classes: {len(labels_sorted)}")

Label2 mapping: {0: 'benign', 1: 'recon', 2: 'ddos', 3: 'bruteforce', 4: 'mitm', 5: 'dos', 6: 'web', 7: 'malware'}
Number of classes: 8


In [21]:
model_type_gb = xgboost.XGBClassifier(objective="multi:softmax", num_class=len(labels_sorted))
model_type_gb.fit(X_train, y_type_train)

y_type_pred = model_type_gb.predict(X_test)

print("=== Attack Type Gradient Boosting ===")
cm = confusion_matrix(y_type_test, y_type_pred, labels=labels_sorted)
report = classification_report(y_type_test, y_type_pred, labels=labels_sorted, target_names=target_names)
mcc = matthews_corrcoef(y_type_test, y_type_pred)
bal = balanced_accuracy_score(y_type_test, y_type_pred)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Attack Type Gradient Boosting ===
Confusion matrix:
[[27025    18     2     4     4     1     1     0]
 [ 1586  5274     6     2     9     5     0     7]
 [  362    17  3185     0    35    31     0     7]
 [   84     3     0   266     1     1     0     5]
 [  126    15    10     1  1434     6     0    13]
 [  187    26    15     2     6  3502     1     4]
 [   85     0     0     0     0     0   481     0]
 [   95    11     2     4     7     2     1  1462]]
Classification report:
              precision    recall  f1-score   support

      benign       0.91      1.00      0.95     27055
       recon       0.98      0.77      0.86      6889
        ddos       0.99      0.88      0.93      3637
  bruteforce       0.95      0.74      0.83       360
        mitm       0.96      0.89      0.92      1605
         dos       0.99      0.94      0.96      3743
         web       0.99      0.85      0.92       566
     malware       0.98      0.92      0.95      1584

    accuracy            

In [25]:
from sklearn.ensemble import RandomForestClassifier


model_type_rf = RandomForestClassifier()
model_type_rf.fit(X_train, y_type_train)

y_type_pred_lr = model_type_rf.predict(X_test)

print("=== Attack Type Logistic Regression ===")
cm = confusion_matrix(y_type_test, y_type_pred_lr, labels=labels_sorted)
report = classification_report(y_type_test, y_type_pred_lr, labels=labels_sorted, target_names=target_names)
mcc = matthews_corrcoef(y_type_test, y_type_pred_lr)
bal = balanced_accuracy_score(y_type_test, y_type_pred_lr)
print(f"Confusion matrix:\n{cm}")
print(f"Classification report:\n{report}")
print(f"Matthews Corrcoef: {mcc:.4f}")
print(f"Balanced accuracy: {bal:.4f}")

=== Attack Type Logistic Regression ===
Confusion matrix:
[[26719   225    36     5    13    29     3    25]
 [ 1620  5226     9     3     5    15     0    11]
 [  370    15  3180     1    22    40     0     9]
 [   90     1     0   264     0     0     0     5]
 [  160    14     8     1  1404     3     0    15]
 [  196    17    15     1    11  3500     0     3]
 [   82     1     1     0     0     0   481     1]
 [  104    17     2     4     5     1     0  1451]]
Classification report:
              precision    recall  f1-score   support

      benign       0.91      0.99      0.95     27055
       recon       0.95      0.76      0.84      6889
        ddos       0.98      0.87      0.92      3637
  bruteforce       0.95      0.73      0.83       360
        mitm       0.96      0.87      0.92      1605
         dos       0.98      0.94      0.95      3743
         web       0.99      0.85      0.92       566
     malware       0.95      0.92      0.93      1584

    accuracy          